### ISSUE TITLE
Ne pas fermer les tags PHP en fin de fichier

### ISSUE THREAD

**Issue by Stoakes** [AzeStudio/Drozor#1]
- Ne pas fermer les tags PHP en fin de fichier : (http://stackoverflow.com/questions/3219383/why-do-some-scripts-omit-the-closing-php-tag)
- Mettre des noms explicites aux fichiers : aj.php ?
- Optimiser les ouvertures fermetures de tags (Ex : ?> <?php, ça ne sert à rien)
-Au lieu d'avoir des fichiers tels isadmin, isconnected .. faire un fichier functions.php dans lequel tu déclares des fonctions que tu pourras utiliser sur tout le site.
- utiliser session_destroy() au lieu de mettre les variables en session à null (cf deco.php)

**Comment by AzeStudio** [comment]
Ouais je l'ai vu récemment, je l'ai donc fait dans certains fichiers mais pas dans tous ;)
je vais y faire partout :)

**Comment by AzeStudio** [comment]
fait pour les tags
le reste je le fait de suite

**Comment by AzeStudio** [comment]
Pour les noms explicites, en fait je fait (ajout_pub.php, connexion.php) pour le formulaire, et une abréviation pour le traitement (aj.php, co.php)

Pour les ouvertures fermetures de tag, j'en ai pas trouvé (et j'ai fait une recherche logicielle), tu en a vu où ?

pas bête pour les fonctions

fait pour le session_destroy :)

**Comment by Stoakes** [comment]
https://github.com/AzeStudio/Drozor/blob/master/aj.php

**Comment by AzeStudio** [comment]
en effet, j'ai oublié les tabulations dans mon analyse logiciel...
il y avait ça aussi dans co.php, c'est supprimé aussi :)
