### ISSUE TITLE
Revoir le stockage du mot de passe

### ISSUE THREAD

**Issue by Stoakes** [AzeStudio/Drozor#2]
Le stockage du mot de passe est trop faible.

- Utiliser une fonction plus sécurisée que md5.
- Ajouter un salt (individualisé serait préférable) au mot de passe pour ne pas être dans les tables de hash des décodeurs.

**Comment by AzeStudio** [comment]
que me propose tu de plus sécurisé que le MD5 ?
je vais voir comment je vais pouvoir y intégrer pour le salt

**Comment by Stoakes** [comment]
Je te propose google : https://www.google.fr/search?q=fonction+hachage+php+s%C3%A9curit%C3%A9

**Comment by AzeStudio** [comment]
:p

**Comment by ThuleMalta** [comment]
Bah moi je te propose sha-256 avec salt.
Chiffrer avec md5 ou ne pas chiffrer revient strictement au même.
Il n'est pas sécurisé (on peut le cracker) et de nombreux dictionnaires existent.

**Comment by AzeStudio** [comment]
Ok je vais voir pour le sha-256 ;)
