### ISSUE TITLE
if($bool == true)

### ISSUE THREAD

**Issue by ThuleMalta** [AzeStudio/Drozor#4]
Cette syntaxe est inutile. Remplace plutôt :
if($bool == true)
par if($bool) et
if($bool == false)
par if (!$bool).

**Comment by AzeStudio** [comment]
Merci je ne connaissait pas :)

**Comment by AzeStudio** [comment]
Tu n'a vu ça que dans inscript.php ?

**Comment by ThuleMalta** [comment]
Je crois.
De toute façon inscript.php est à revoir de zéro.

**Comment by AzeStudio** [comment]
Ok ;)
Oui c'est sur :+1:
